input.onButtonPressed(Button.A, function on_button_pressed_a() {
    basic.showLeds(`
        . . . # #
                        . . . # #
                        . . . # #
                        . # # # #
                        # # # # #
    `)
    basic.pause(25)
    basic.showLeds(`
        . . . # #
                        . . . # #
                        . # # # #
                        . # # # .
                        # # # . .
    `)
    basic.pause(25)
    for (let index = 0; index < 6; index++) {
        basic.showLeds(`
            . # # # .
                                    . # # # .
                                    . . # . .
                                    . # # # .
                                    # # . # .
        `)
        basic.pause(10)
        basic.showLeds(`
            . # # # .
                                    . # # # .
                                    . . # . .
                                    . # # # .
                                    . # . # #
        `)
        basic.pause(5)
        basic.showLeds(`
            # # # . .
                                    # # # . .
                                    . # . . .
                                    . # . . .
                                    # . # . .
        `)
        basic.pause(5)
        basic.showLeds(`
            . . # # #
                                    . . # # #
                                    . . . # .
                                    . . . # .
                                    . . # . #
        `)
    }
    basic.showLeds(`
        # # # # .
                        # . . . .
                        # . . # .
                        # . . . #
                        # # # # #
    `)
    basic.pause(5)
    basic.showLeds(`
        # # # # .
                        # . . . .
                        # # # . .
                        # . . . .
                        # # # # .
    `)
    basic.pause(5)
    basic.showLeds(`
        # # # # #
                        . . # . .
                        . . # . .
                        . . # . .
                        . . # . .
    `)
    basic.showString("RICK ROLLED")
})
music.setVolume(255)
music.playTone(349, music.beat(BeatFraction.Whole))
music.playTone(349, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Half))
music.playTone(392, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(262, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Half))
music.playTone(392, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(440, music.beat(BeatFraction.Half))
music.playTone(440, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(523, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(466, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(440, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Whole))
music.playTone(349, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Half))
music.playTone(392, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(262, music.beat(BeatFraction.Half))
music.playTone(262, music.beat(BeatFraction.Double))
music.rest(music.beat(BeatFraction.Sixteenth))
music.rest(music.beat(BeatFraction.Whole))
music.playTone(262, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(262, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(330, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Whole))
music.playTone(349, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Half))
music.playTone(392, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(262, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Half))
music.playTone(392, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(440, music.beat(BeatFraction.Half))
music.playTone(440, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(523, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(466, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(440, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Whole))
music.playTone(349, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Half))
music.playTone(392, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(262, music.beat(BeatFraction.Half))
music.playTone(262, music.beat(BeatFraction.Double))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(330, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Sixteenth))
music.rest(music.beat(BeatFraction.Whole))
music.playTone(349, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Whole))
music.playTone(294, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(330, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(330, music.beat(BeatFraction.Half))
music.playTone(330, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(262, music.beat(BeatFraction.Half))
music.playTone(262, music.beat(BeatFraction.Double))
music.rest(music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Half))
music.playTone(294, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(330, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(262, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(523, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Half))
music.playTone(523, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Double))
music.rest(music.beat(BeatFraction.Whole))
music.playTone(294, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(330, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Half))
music.playTone(330, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Half))
music.playTone(262, music.beat(BeatFraction.Double))
music.rest(music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Half))
music.playTone(294, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(330, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(262, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(440, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Whole))
music.playTone(349, music.beat(BeatFraction.Half))
music.playTone(349, music.beat(BeatFraction.Double))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(440, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(440, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(262, music.beat(BeatFraction.Double))
music.rest(music.beat(BeatFraction.Whole))
music.playTone(294, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(330, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Half))
music.playTone(392, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(440, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Half))
music.playTone(392, music.beat(BeatFraction.Whole))
music.playTone(262, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(440, music.beat(BeatFraction.Quarter))
music.playTone(440, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(440, music.beat(BeatFraction.Quarter))
music.playTone(440, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Half))
music.playTone(392, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(262, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Quarter))
music.playTone(392, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Quarter))
music.playTone(392, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Quarter))
music.playTone(349, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(330, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(262, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(294, music.beat(BeatFraction.Quarter))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(349, music.beat(BeatFraction.Whole))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(392, music.beat(BeatFraction.Half))
music.rest(music.beat(BeatFraction.Sixteenth))
music.playTone(330, music.beat(BeatFraction.Quarter))
